# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WBProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WBProject
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'RealmSwift'
  pod 'RevealingSplashView'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Segmentio'

end
